# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rake db:seed (or created alongside the db with db:setup).
#
# Examples:
#
#   cities = City.create([{ name: 'Chicago' }, { name: 'Copenhagen' }])
#   Mayor.create(name: 'Emanuel', city: cities.first)

User.create(email: 'admin@engines.onl', username: 'admin', password: 'EngOS2014', password_confirmation: 'EngOS2014')
Language.create(record_name: 'PHP')
Language.create(record_name: 'Ruby')
Language.create(record_name: 'Python')
Language.create(record_name: 'Java')
Framework.create(record_name: 'Apache', language_id: 1)
Framework.create(record_name: 'Nginx', language_id: 1)
Framework.create(record_name: 'Rails', language_id: 2)
Framework.create(record_name: 'Sinatra', language_id: 2)
Framework.create(record_name: 'Django', language_id: 3)
Framework.create(record_name: 'Flask', language_id: 3)
Framework.create(record_name: 'Pyramid', language_id: 3)
Framework.create(record_name: 'Jetty', language_id: 4)
Framework.create(record_name: 'Tomcat', language_id: 4)
License.create(record_name: 'GPL v2')
License.create(record_name: 'GPL v3')
License.create(record_name: 'MIT')
License.create(record_name: 'Apache v2')
DeploymentType.create(record_name: 'Web')
DeploymentType.create(record_name: 'Worker')
ServiceType.create(record_name: 'Volume')
ServiceType.create(record_name: 'DNS')
ServiceType.create(record_name: 'Cron')
ServiceType.create(record_name: 'Database')
Publisher.create(record_name: 'Engines')
Publisher.create(record_name: 'Odoo S.A.')
Software.create(record_name: 'Etherpad', publisher_id: 1)
Software.create(record_name: 'Odoo', publisher_id: 2)
ServiceBlueprint.create(record_name: "MySQL", publisher_id: 1, service_type_id: 4, persistent: true, image_name: "engines/mysql", variables_attributes: [{record_name: "database_host", value: "mysql.engines.internal"}, {record_name: "database_name", value: "dunno"}])
ServiceBlueprint.create(record_name: "Postgres SQL", publisher_id: 1, service_type_id: 4, persistent: true, image_name: "engines/pgsql")
SoftwareVersion.create(record_name: 'v2', title: "Etherpad (version 2.0)", software_id: 1)
BlueprintVersion.create(record_name: 'v0.0.0.1', software_version_id: 1)
